### ISSUE TITLE
[BUG] cant read messages in servers or in channels and getting cli cores error invalid body

### ISSUE THREAD

**Issue by 9xN** [MyPasswordIsWeak/cli-cord#15]
![Screen Shot 2021-11-22 at 8 45 17 PM](https://user-images.githubusercontent.com/94141577/142968515-48645071-932e-4a41-ab00-fb8f57acd1bc.png)

**Comment by MyPasswordIsWeak** [comment]
i can't seem to reproduce this error. could you send your log file so i can see if anything is odd there?

**Comment by 9xN** [comment]
[20:44:54][CLI-CORE] === ERROR ===
[20:44:55][CLI-CORE] Discord client is ready
[20:53:16][INIT] Loaded default theme
[20:53:16][INIT] Dependency versions: -- blessed@0.1.81, cli-core@67e6132d1d5cda25631bcc39f3a406a2b70708b4, node-fetch@2.6.5, tr46@0.0.3, webidl-conversions@3.0.1, whatwg-url@5.0.0, ws@7.5.5 --
[20:53:16][INIT] Cli-core versions: -- package.json: 0.2.0 -- git: 73451cdb01b0854a0d208ce7c6885653f57c5b6e --
[20:53:18][INIT][KEYS] Done starting input
[20:53:18][CLI-CORE] === ERROR ===
[20:53:18][CLI-CORE] Name: Error
[20:53:18][CLI-CORE] Message: Invalid Form Body
[20:53:18][CLI-CORE] Stacktrace: Error: Invalid Form Body
[20:53:18][CLI-CORE]    |    at Requests.perform (/Users/atg/cli-cord/node_modules/cli-core/lib/structures/Requests.js:150:10)
[20:53:18][CLI-CORE]    |    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[20:53:18][CLI-CORE]    |    at async Client.fetchChannel (/Users/atg/cli-cord/node_modules/cli-core/lib/client/Client.js:108:16)
[20:53:18][CLI-CORE] === ERROR ===
[20:53:18][CLI-CORE] Discord client is ready
[23:24:41][INIT] Loaded default theme
[23:24:41][INIT] Dependency versions: -- blessed@0.1.81, cli-core@67e6132d1d5cda25631bcc39f3a406a2b70708b4, node-fetch@2.6.5, tr46@0.0.3, webidl-conversions@3.0.1, whatwg-url@5.0.0, ws@7.5.5 --
[23:24:41][INIT] Cli-core versions: -- package.json: 0.2.0 -- git: 73451cdb01b0854a0d208ce7c6885653f57c5b6e --
[23:24:43][INIT][KEYS] Done starting input
[23:24:43][CLI-CORE] === ERROR ===
[23:24:43][CLI-CORE] Name: Error
[23:24:43][CLI-CORE] Message: Invalid Form Body
[23:24:43][CLI-CORE] Stacktrace: Error: Invalid Form Body
[23:24:43][CLI-CORE]    |    at Requests.perform (/Users/atg/cli-cord/node_modules/cli-core/lib/structures/Requests.js:150:10)
[23:24:43][CLI-CORE]    |    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[23:24:43][CLI-CORE]    |    at async Client.fetchChannel (/Users/atg/cli-cord/node_modules/cli-core/lib/client/Client.js:108:16)
[23:24:43][CLI-CORE] === ERROR ===
[23:24:44][CLI-CORE] Discord client is ready

**Comment by 9xN** [comment]
how are you supposed to select a server and channel to message in because no matter what key i press it just keeps me in the server selection screen

**Comment by MyPasswordIsWeak** [comment]
you press on `c` to go to the channel switcher, and then press `w` to start composing a message, regarding your issue, i honestly have no clue what's happening, discord docs state there have been no changes in the get channel endpoint yet for some reason it's complaining? Could you try running `npm run update` and then re-running cli-cord to see if that fixed it, i pushed a commit that might change it, i'm not sure

**Comment by 9xN** [comment]
yea no matter what i press it wont let me write messages or escape the server selector much less even look at channels i think thats probably the issue

**Comment by 9xN** [comment]
yea still doesnt work whats your discord itll be easier to talk or just add me social#2435

**Comment by MyPasswordIsWeak** [comment]
i've sent you a friend request
